# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeamPoker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.mainPage)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.mainPage)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.mainPage)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.groupBox = QtWidgets.QGroupBox(self.mainPage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(70, 70))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, 20)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.mainPage)
        self.hostGamePage = QtWidgets.QWidget()
        self.hostGamePage.setObjectName("hostGamePage")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.hostGamePage)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(402, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.label_9 = QtWidgets.QLabel(self.hostGamePage)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.hostGamePage)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.hostGamePage)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.hostGamePage)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_10.addWidget(self.lineEdit_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.label_13 = QtWidgets.QLabel(self.hostGamePage)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.hostGamePage)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.hostGamePage)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.hostGamePage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.hostGamePage)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox.setSpecialValueText("")
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setSingleStep(0.25)
        self.doubleSpinBox.setProperty("value", 0.25)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.hostGamePage)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.hostGamePage)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.hostGamePage)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.hostGamePage)
        self.doubleSpinBox_2.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBox_2.setMaximum(200.0)
        self.doubleSpinBox_2.setSingleStep(0.25)
        self.doubleSpinBox_2.setProperty("value", 0.5)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.label_12 = QtWidgets.QLabel(self.hostGamePage)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.hostGamePage)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.hostGamePage)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.label_10 = QtWidgets.QLabel(self.hostGamePage)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.pushButton_8 = QtWidgets.QPushButton(self.hostGamePage)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_13.addWidget(self.pushButton_8)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem14 = QtWidgets.QSpacerItem(402, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.stackedWidget.addWidget(self.hostGamePage)
        self.gamePlayPage = QtWidgets.QWidget()
        self.gamePlayPage.setObjectName("gamePlayPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gamePlayPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.player4 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.player4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.player4.setObjectName("player4")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.player4)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.player4_icon = QtWidgets.QPushButton(self.player4)
        self.player4_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player4_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player4_icon.setText("")
        self.player4_icon.setObjectName("player4_icon")
        self.horizontalLayout_48.addWidget(self.player4_icon)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.player4_name = QtWidgets.QLabel(self.player4)
        self.player4_name.setObjectName("player4_name")
        self.horizontalLayout_49.addWidget(self.player4_name)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem15)
        self.verticalLayout_24.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.player4_money_available = QtWidgets.QLabel(self.player4)
        self.player4_money_available.setObjectName("player4_money_available")
        self.horizontalLayout_52.addWidget(self.player4_money_available)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem16)
        self.verticalLayout_24.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_48.addLayout(self.verticalLayout_24)
        self.verticalLayout_23.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.player4_card1 = QtWidgets.QPushButton(self.player4)
        self.player4_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player4_card1.setText("")
        self.player4_card1.setObjectName("player4_card1")
        self.horizontalLayout_23.addWidget(self.player4_card1)
        self.player4_card2 = QtWidgets.QPushButton(self.player4)
        self.player4_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player4_card2.setText("")
        self.player4_card2.setObjectName("player4_card2")
        self.horizontalLayout_23.addWidget(self.player4_card2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.player4_action = QtWidgets.QLabel(self.player4)
        self.player4_action.setObjectName("player4_action")
        self.horizontalLayout_76.addWidget(self.player4_action)
        self.verticalLayout_30.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.player4_dealer = QtWidgets.QPushButton(self.player4)
        self.player4_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player4_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player4_dealer.setText("")
        self.player4_dealer.setObjectName("player4_dealer")
        self.horizontalLayout_77.addWidget(self.player4_dealer)
        self.verticalLayout_30.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_23.addLayout(self.verticalLayout_30)
        self.verticalLayout_23.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_51.addLayout(self.verticalLayout_23)
        self.horizontalLayout_15.addWidget(self.player4)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.player5 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.player5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.player5.setObjectName("player5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.player5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.player5_icon = QtWidgets.QPushButton(self.player5)
        self.player5_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player5_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player5_icon.setText("")
        self.player5_icon.setObjectName("player5_icon")
        self.horizontalLayout_32.addWidget(self.player5_icon)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.player5_name = QtWidgets.QLabel(self.player5)
        self.player5_name.setObjectName("player5_name")
        self.horizontalLayout_33.addWidget(self.player5_name)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem19)
        self.verticalLayout_18.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.player5_money_available = QtWidgets.QLabel(self.player5)
        self.player5_money_available.setObjectName("player5_money_available")
        self.horizontalLayout_34.addWidget(self.player5_money_available)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem20)
        self.verticalLayout_18.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_32.addLayout(self.verticalLayout_18)
        self.player5_card1 = QtWidgets.QPushButton(self.player5)
        self.player5_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player5_card1.setText("")
        self.player5_card1.setObjectName("player5_card1")
        self.horizontalLayout_32.addWidget(self.player5_card1)
        self.player5_card2 = QtWidgets.QPushButton(self.player5)
        self.player5_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player5_card2.setText("")
        self.player5_card2.setObjectName("player5_card2")
        self.horizontalLayout_32.addWidget(self.player5_card2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem21)
        self.player5_dealer = QtWidgets.QPushButton(self.player5)
        self.player5_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player5_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player5_dealer.setText("")
        self.player5_dealer.setObjectName("player5_dealer")
        self.horizontalLayout_14.addWidget(self.player5_dealer)
        self.player5_action = QtWidgets.QLabel(self.player5)
        self.player5_action.setObjectName("player5_action")
        self.horizontalLayout_14.addWidget(self.player5_action)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem22)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19.addLayout(self.verticalLayout_17)
        self.horizontalLayout_15.addWidget(self.player5)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem23)
        self.player6 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.player6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.player6.setObjectName("player6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.player6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setSpacing(0)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem24)
        self.player6_name = QtWidgets.QLabel(self.player6)
        self.player6_name.setObjectName("player6_name")
        self.horizontalLayout_61.addWidget(self.player6_name)
        self.verticalLayout_47.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem25)
        self.player5_money_available_2 = QtWidgets.QLabel(self.player6)
        self.player5_money_available_2.setObjectName("player5_money_available_2")
        self.horizontalLayout_62.addWidget(self.player5_money_available_2)
        self.verticalLayout_47.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_53.addLayout(self.verticalLayout_47)
        self.player6_icon = QtWidgets.QPushButton(self.player6)
        self.player6_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player6_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player6_icon.setText("")
        self.player6_icon.setObjectName("player6_icon")
        self.horizontalLayout_53.addWidget(self.player6_icon)
        self.verticalLayout_46.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.player6_action = QtWidgets.QLabel(self.player6)
        self.player6_action.setObjectName("player6_action")
        self.horizontalLayout_80.addWidget(self.player6_action)
        self.verticalLayout_45.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.player6_dealer = QtWidgets.QPushButton(self.player6)
        self.player6_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player6_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player6_dealer.setText("")
        self.player6_dealer.setObjectName("player6_dealer")
        self.horizontalLayout_81.addWidget(self.player6_dealer)
        self.verticalLayout_45.addLayout(self.horizontalLayout_81)
        self.horizontalLayout_26.addLayout(self.verticalLayout_45)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.player6_card1 = QtWidgets.QPushButton(self.player6)
        self.player6_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player6_card1.setText("")
        self.player6_card1.setObjectName("player6_card1")
        self.horizontalLayout_26.addWidget(self.player6_card1)
        self.player6_card2 = QtWidgets.QPushButton(self.player6)
        self.player6_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player6_card2.setText("")
        self.player6_card2.setObjectName("player6_card2")
        self.horizontalLayout_26.addWidget(self.player6_card2)
        self.verticalLayout_46.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25.addLayout(self.verticalLayout_46)
        self.horizontalLayout_15.addWidget(self.player6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem27)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.player3_icon = QtWidgets.QPushButton(self.groupBox_2)
        self.player3_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player3_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player3_icon.setText("")
        self.player3_icon.setObjectName("player3_icon")
        self.horizontalLayout_29.addWidget(self.player3_icon)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.player3_name = QtWidgets.QLabel(self.groupBox_2)
        self.player3_name.setObjectName("player3_name")
        self.horizontalLayout_30.addWidget(self.player3_name)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem28)
        self.verticalLayout_16.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.player3_money_available = QtWidgets.QLabel(self.groupBox_2)
        self.player3_money_available.setObjectName("player3_money_available")
        self.horizontalLayout_31.addWidget(self.player3_money_available)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem29)
        self.verticalLayout_16.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_16)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.player3_card1 = QtWidgets.QPushButton(self.groupBox_2)
        self.player3_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player3_card1.setText("")
        self.player3_card1.setObjectName("player3_card1")
        self.horizontalLayout_18.addWidget(self.player3_card1)
        self.player3_card2 = QtWidgets.QPushButton(self.groupBox_2)
        self.player3_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player3_card2.setText("")
        self.player3_card2.setObjectName("player3_card2")
        self.horizontalLayout_18.addWidget(self.player3_card2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem30)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.player3_action = QtWidgets.QLabel(self.groupBox_2)
        self.player3_action.setObjectName("player3_action")
        self.horizontalLayout_64.addWidget(self.player3_action)
        self.verticalLayout_29.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.player3_dealer = QtWidgets.QPushButton(self.groupBox_2)
        self.player3_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player3_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player3_dealer.setText("")
        self.player3_dealer.setObjectName("player3_dealer")
        self.horizontalLayout_65.addWidget(self.player3_dealer)
        self.verticalLayout_29.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_18.addLayout(self.verticalLayout_29)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_50.addLayout(self.verticalLayout_15)
        self.horizontalLayout_16.addWidget(self.groupBox_2)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem31)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.cards_burnedCards = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_burnedCards.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_burnedCards.setMaximumSize(QtCore.QSize(70, 105))
        self.cards_burnedCards.setText("")
        self.cards_burnedCards.setObjectName("cards_burnedCards")
        self.horizontalLayout_44.addWidget(self.cards_burnedCards)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cards_tableCard1 = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_tableCard1.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_tableCard1.setText("")
        self.cards_tableCard1.setObjectName("cards_tableCard1")
        self.horizontalLayout_2.addWidget(self.cards_tableCard1)
        self.cards_tableCard2 = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_tableCard2.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_tableCard2.setText("")
        self.cards_tableCard2.setObjectName("cards_tableCard2")
        self.horizontalLayout_2.addWidget(self.cards_tableCard2)
        self.cards_tableCard3 = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_tableCard3.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_tableCard3.setText("")
        self.cards_tableCard3.setObjectName("cards_tableCard3")
        self.horizontalLayout_2.addWidget(self.cards_tableCard3)
        self.cards_tableCard4 = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_tableCard4.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_tableCard4.setText("")
        self.cards_tableCard4.setObjectName("cards_tableCard4")
        self.horizontalLayout_2.addWidget(self.cards_tableCard4)
        self.cards_tableCard5 = QtWidgets.QPushButton(self.gamePlayPage)
        self.cards_tableCard5.setMinimumSize(QtCore.QSize(70, 105))
        self.cards_tableCard5.setText("")
        self.cards_tableCard5.setObjectName("cards_tableCard5")
        self.horizontalLayout_2.addWidget(self.cards_tableCard5)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_2)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem32)
        self.player7 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.player7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.player7.setObjectName("player7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.player7)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem33)
        self.player7_name = QtWidgets.QLabel(self.player7)
        self.player7_name.setObjectName("player7_name")
        self.horizontalLayout_39.addWidget(self.player7_name)
        self.verticalLayout_37.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem34)
        self.player6_money_available = QtWidgets.QLabel(self.player7)
        self.player6_money_available.setObjectName("player6_money_available")
        self.horizontalLayout_40.addWidget(self.player6_money_available)
        self.verticalLayout_37.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_38.addLayout(self.verticalLayout_37)
        self.player7_icon = QtWidgets.QPushButton(self.player7)
        self.player7_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player7_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player7_icon.setText("")
        self.player7_icon.setObjectName("player7_icon")
        self.horizontalLayout_38.addWidget(self.player7_icon)
        self.verticalLayout_36.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.player7_action = QtWidgets.QLabel(self.player7)
        self.player7_action.setObjectName("player7_action")
        self.horizontalLayout_72.addWidget(self.player7_action)
        self.verticalLayout_35.addLayout(self.horizontalLayout_72)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.player7_dealer = QtWidgets.QPushButton(self.player7)
        self.player7_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player7_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player7_dealer.setText("")
        self.player7_dealer.setObjectName("player7_dealer")
        self.horizontalLayout_73.addWidget(self.player7_dealer)
        self.verticalLayout_35.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_21.addLayout(self.verticalLayout_35)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem35)
        self.player7_card1 = QtWidgets.QPushButton(self.player7)
        self.player7_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player7_card1.setText("")
        self.player7_card1.setObjectName("player7_card1")
        self.horizontalLayout_21.addWidget(self.player7_card1)
        self.player7_card2 = QtWidgets.QPushButton(self.player7)
        self.player7_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player7_card2.setText("")
        self.player7_card2.setObjectName("player7_card2")
        self.horizontalLayout_21.addWidget(self.player7_card2)
        self.verticalLayout_36.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17.addLayout(self.verticalLayout_36)
        self.horizontalLayout_16.addWidget(self.player7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem36)
        self.label_result = QtWidgets.QLabel(self.gamePlayPage)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_46.addWidget(self.label_result)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem37)
        self.verticalLayout_8.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.groupBox_4 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.player2_icon = QtWidgets.QPushButton(self.groupBox_4)
        self.player2_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player2_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player2_icon.setText("")
        self.player2_icon.setObjectName("player2_icon")
        self.horizontalLayout_58.addWidget(self.player2_icon)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.player2_name = QtWidgets.QLabel(self.groupBox_4)
        self.player2_name.setObjectName("player2_name")
        self.horizontalLayout_59.addWidget(self.player2_name)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem38)
        self.verticalLayout_28.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.player2_money_available = QtWidgets.QLabel(self.groupBox_4)
        self.player2_money_available.setObjectName("player2_money_available")
        self.horizontalLayout_60.addWidget(self.player2_money_available)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem39)
        self.verticalLayout_28.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_58.addLayout(self.verticalLayout_28)
        self.verticalLayout_27.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.player2_card1 = QtWidgets.QPushButton(self.groupBox_4)
        self.player2_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player2_card1.setText("")
        self.player2_card1.setObjectName("player2_card1")
        self.horizontalLayout_24.addWidget(self.player2_card1)
        self.player2_card2 = QtWidgets.QPushButton(self.groupBox_4)
        self.player2_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player2_card2.setText("")
        self.player2_card2.setObjectName("player2_card2")
        self.horizontalLayout_24.addWidget(self.player2_card2)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem40)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.player2_action = QtWidgets.QLabel(self.groupBox_4)
        self.player2_action.setObjectName("player2_action")
        self.horizontalLayout_78.addWidget(self.player2_action)
        self.verticalLayout_43.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.player2_dealer = QtWidgets.QPushButton(self.groupBox_4)
        self.player2_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player2_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player2_dealer.setText("")
        self.player2_dealer.setObjectName("player2_dealer")
        self.horizontalLayout_79.addWidget(self.player2_dealer)
        self.verticalLayout_43.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_24.addLayout(self.verticalLayout_43)
        self.verticalLayout_27.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_57.addLayout(self.verticalLayout_27)
        self.horizontalLayout_20.addWidget(self.groupBox_4)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem41)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_38 = QtWidgets.QLabel(self.gamePlayPage)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_47.addWidget(self.label_38)
        self.label_potValue = QtWidgets.QLabel(self.gamePlayPage)
        self.label_potValue.setObjectName("label_potValue")
        self.horizontalLayout_47.addWidget(self.label_potValue)
        self.icon_potSize = QtWidgets.QPushButton(self.gamePlayPage)
        self.icon_potSize.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_potSize.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_potSize.setText("")
        self.icon_potSize.setObjectName("icon_potSize")
        self.horizontalLayout_47.addWidget(self.icon_potSize)
        self.verticalLayout_7.addLayout(self.horizontalLayout_47)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem42)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem43)
        self.player8 = QtWidgets.QGroupBox(self.gamePlayPage)
        self.player8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.player8.setObjectName("player8")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.player8)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setSpacing(0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem44)
        self.player8_name = QtWidgets.QLabel(self.player8)
        self.player8_name.setObjectName("player8_name")
        self.horizontalLayout_54.addWidget(self.player8_name)
        self.verticalLayout_41.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem45)
        self.player7_money_available = QtWidgets.QLabel(self.player8)
        self.player7_money_available.setObjectName("player7_money_available")
        self.horizontalLayout_55.addWidget(self.player7_money_available)
        self.verticalLayout_41.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_41.addLayout(self.verticalLayout_41)
        self.player8_icon = QtWidgets.QPushButton(self.player8)
        self.player8_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player8_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player8_icon.setText("")
        self.player8_icon.setObjectName("player8_icon")
        self.horizontalLayout_41.addWidget(self.player8_icon)
        self.verticalLayout_40.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.player8_action = QtWidgets.QLabel(self.player8)
        self.player8_action.setObjectName("player8_action")
        self.horizontalLayout_74.addWidget(self.player8_action)
        self.verticalLayout_39.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.player8_dealer = QtWidgets.QPushButton(self.player8)
        self.player8_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player8_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player8_dealer.setText("")
        self.player8_dealer.setObjectName("player8_dealer")
        self.horizontalLayout_75.addWidget(self.player8_dealer)
        self.verticalLayout_39.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_27.addLayout(self.verticalLayout_39)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem46)
        self.player8_card1 = QtWidgets.QPushButton(self.player8)
        self.player8_card1.setMinimumSize(QtCore.QSize(50, 85))
        self.player8_card1.setText("")
        self.player8_card1.setObjectName("player8_card1")
        self.horizontalLayout_27.addWidget(self.player8_card1)
        self.player8_card2 = QtWidgets.QPushButton(self.player8)
        self.player8_card2.setMinimumSize(QtCore.QSize(50, 85))
        self.player8_card2.setText("")
        self.player8_card2.setObjectName("player8_card2")
        self.horizontalLayout_27.addWidget(self.player8_card2)
        self.verticalLayout_40.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_22.addLayout(self.verticalLayout_40)
        self.horizontalLayout_20.addWidget(self.player8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        spacerItem47 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem47)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.tabWidget = QtWidgets.QTabWidget(self.gamePlayPage)
        self.tabWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_server_settings = QtWidgets.QWidget()
        self.tab_server_settings.setObjectName("tab_server_settings")
        self.tabWidget.addTab(self.tab_server_settings, "")
        self.horizontalLayout_42.addWidget(self.tabWidget)
        self.widget_2 = QtWidgets.QWidget(self.gamePlayPage)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_42.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.gamePlayPage)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem48)
        self.player1_dealer = QtWidgets.QPushButton(self.widget_3)
        self.player1_dealer.setMinimumSize(QtCore.QSize(40, 40))
        self.player1_dealer.setMaximumSize(QtCore.QSize(40, 40))
        self.player1_dealer.setText("")
        self.player1_dealer.setObjectName("player1_dealer")
        self.horizontalLayout_28.addWidget(self.player1_dealer)
        self.player1_action = QtWidgets.QLabel(self.widget_3)
        self.player1_action.setObjectName("player1_action")
        self.horizontalLayout_28.addWidget(self.player1_action)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem49)
        self.verticalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.player1_icon = QtWidgets.QPushButton(self.widget_3)
        self.player1_icon.setMinimumSize(QtCore.QSize(70, 70))
        self.player1_icon.setMaximumSize(QtCore.QSize(70, 70))
        self.player1_icon.setText("")
        self.player1_icon.setObjectName("player1_icon")
        self.horizontalLayout_36.addWidget(self.player1_icon)
        self.verticalLayout_14.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem50)
        self.player1_name = QtWidgets.QLabel(self.widget_3)
        self.player1_name.setObjectName("player1_name")
        self.horizontalLayout_37.addWidget(self.player1_name)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem51)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem52)
        self.player1_money_available = QtWidgets.QLabel(self.widget_3)
        self.player1_money_available.setObjectName("player1_money_available")
        self.horizontalLayout_43.addWidget(self.player1_money_available)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem53)
        self.verticalLayout_14.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_35.addLayout(self.verticalLayout_14)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.player1_card1 = QtWidgets.QPushButton(self.widget_3)
        self.player1_card1.setMinimumSize(QtCore.QSize(90, 125))
        self.player1_card1.setText("")
        self.player1_card1.setObjectName("player1_card1")
        self.horizontalLayout_45.addWidget(self.player1_card1)
        self.player1_card2 = QtWidgets.QPushButton(self.widget_3)
        self.player1_card2.setMinimumSize(QtCore.QSize(90, 125))
        self.player1_card2.setText("")
        self.player1_card2.setObjectName("player1_card2")
        self.horizontalLayout_45.addWidget(self.player1_card2)
        self.horizontalLayout_35.addLayout(self.horizontalLayout_45)
        self.verticalLayout_13.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_42.addWidget(self.widget_3)
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem54)
        self.widget = QtWidgets.QWidget(self.gamePlayPage)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(1, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem55 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem55)
        self.action_call = QtWidgets.QPushButton(self.widget)
        self.action_call.setMinimumSize(QtCore.QSize(100, 50))
        self.action_call.setMaximumSize(QtCore.QSize(100, 50))
        self.action_call.setObjectName("action_call")
        self.verticalLayout_9.addWidget(self.action_call)
        self.action_fold = QtWidgets.QPushButton(self.widget)
        self.action_fold.setMinimumSize(QtCore.QSize(100, 50))
        self.action_fold.setMaximumSize(QtCore.QSize(100, 50))
        self.action_fold.setObjectName("action_fold")
        self.verticalLayout_9.addWidget(self.action_fold)
        spacerItem56 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem56)
        self.horizontalLayout_42.addWidget(self.widget)
        self.verticalWidget = QtWidgets.QWidget(self.gamePlayPage)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_10.setContentsMargins(1, -1, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem57 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem57)
        self.action_raise = QtWidgets.QPushButton(self.verticalWidget)
        self.action_raise.setMinimumSize(QtCore.QSize(100, 50))
        self.action_raise.setMaximumSize(QtCore.QSize(100, 50))
        self.action_raise.setObjectName("action_raise")
        self.verticalLayout_10.addWidget(self.action_raise)
        self.widget1 = QtWidgets.QWidget(self.verticalWidget)
        self.widget1.setMinimumSize(QtCore.QSize(100, 50))
        self.widget1.setMaximumSize(QtCore.QSize(100, 50))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_11.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_raise_ammount = QtWidgets.QLineEdit(self.widget1)
        self.line_raise_ammount.setObjectName("line_raise_ammount")
        self.verticalLayout_11.addWidget(self.line_raise_ammount)
        self.horizontalSlider = QtWidgets.QSlider(self.widget1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_11.addWidget(self.horizontalSlider)
        self.verticalLayout_10.addWidget(self.widget1)
        spacerItem58 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem58)
        self.horizontalLayout_42.addWidget(self.verticalWidget)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem59)
        self.verticalWidget_2 = QtWidgets.QWidget(self.gamePlayPage)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_12.setContentsMargins(1, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem60 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem60)
        self.action_buy_in = QtWidgets.QPushButton(self.verticalWidget_2)
        self.action_buy_in.setMinimumSize(QtCore.QSize(100, 50))
        self.action_buy_in.setMaximumSize(QtCore.QSize(100, 50))
        self.action_buy_in.setObjectName("action_buy_in")
        self.verticalLayout_12.addWidget(self.action_buy_in)
        self.action_sit_out = QtWidgets.QPushButton(self.verticalWidget_2)
        self.action_sit_out.setMinimumSize(QtCore.QSize(100, 50))
        self.action_sit_out.setMaximumSize(QtCore.QSize(100, 50))
        self.action_sit_out.setObjectName("action_sit_out")
        self.verticalLayout_12.addWidget(self.action_sit_out)
        spacerItem61 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem61)
        self.horizontalLayout_42.addWidget(self.verticalWidget_2)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem62)
        self.verticalLayout_8.addLayout(self.horizontalLayout_42)
        self.stackedWidget.addWidget(self.gamePlayPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Totally amazingly simple multiplayer </p><p align=\"center\"><img src=\":/other_icons/other_icons/main_logo.png\"/></p><p align=\"center\"><span style=\" font-size:18pt;\">TeamPoker™</span></p><p align=\"center\">inspider by the boredom that was the 2020 Coronavirus Pandemic.</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Host a Game"))
        self.pushButton.setText(_translate("MainWindow", "Join a Game"))
        self.groupBox.setTitle(_translate("MainWindow", "Player Settings"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Name:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Host Game Settings</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Game Name:"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Something Something Something Dark Side..."))
        self.label_7.setText(_translate("MainWindow", "Starting Ammount:"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "10.0"))
        self.label_2.setText(_translate("MainWindow", "Small Blinds:"))
        self.label_5.setText(_translate("MainWindow", "Currency:"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "RON"))
        self.label_4.setText(_translate("MainWindow", "Big Blinds:"))
        self.label_6.setText(_translate("MainWindow", "Blind Raise Interval:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "No Blind Raising"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "10 Minutes"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "20 Minutes"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "30 Minutes"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Start Hosting A Game"))
        self.player4_name.setText(_translate("MainWindow", "TextLabel"))
        self.player4_money_available.setText(_translate("MainWindow", "0.00"))
        self.player4_action.setText(_translate("MainWindow", "TextLabel"))
        self.player5_name.setText(_translate("MainWindow", "TextLabel"))
        self.player5_money_available.setText(_translate("MainWindow", "0.00"))
        self.player5_action.setText(_translate("MainWindow", "TextLabel"))
        self.player6_name.setText(_translate("MainWindow", "TextLabel"))
        self.player5_money_available_2.setText(_translate("MainWindow", "0.00"))
        self.player6_action.setText(_translate("MainWindow", "TextLabel"))
        self.player3_name.setText(_translate("MainWindow", "TextLabel"))
        self.player3_money_available.setText(_translate("MainWindow", "0.00"))
        self.player3_action.setText(_translate("MainWindow", "TextLabel"))
        self.player7_name.setText(_translate("MainWindow", "TextLabel"))
        self.player6_money_available.setText(_translate("MainWindow", "0.00"))
        self.player7_action.setText(_translate("MainWindow", "TextLabel"))
        self.label_result.setText(_translate("MainWindow", "TextLabel"))
        self.player2_name.setText(_translate("MainWindow", "TextLabel"))
        self.player2_money_available.setText(_translate("MainWindow", "0.00"))
        self.player2_action.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "Current Pot:"))
        self.label_potValue.setText(_translate("MainWindow", "TextLabel"))
        self.player8_name.setText(_translate("MainWindow", "TextLabel"))
        self.player7_money_available.setText(_translate("MainWindow", "0.00"))
        self.player8_action.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Table History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Money Stats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_server_settings), _translate("MainWindow", "Server Stuff"))
        self.player1_action.setText(_translate("MainWindow", "TextLabel"))
        self.player1_name.setText(_translate("MainWindow", "TextLabel"))
        self.player1_money_available.setText(_translate("MainWindow", "0.00"))
        self.action_call.setText(_translate("MainWindow", "Call"))
        self.action_fold.setText(_translate("MainWindow", "Fold"))
        self.action_raise.setText(_translate("MainWindow", "Raise"))
        self.action_buy_in.setText(_translate("MainWindow", "Buy-In"))
        self.action_sit_out.setText(_translate("MainWindow", "Sit Out Next Turn"))

import pixels_rc
